// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RznMicro.Atlanta.Database.Feature;

#nullable disable

namespace RznMicro.Atlanta.Database.Migrations
{
    [DbContext(typeof(DefaultDataBaseContext))]
    partial class DefaultDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RznMicro.Atlanta.Feature.Address.Model.AddressEntity", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("TypeOfAddress")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdUser");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("RznMicro.Atlanta.Feature.User.Model.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("RznMicro.Atlanta.Feature.Address.Model.AddressEntity", b =>
                {
                    b.HasOne("RznMicro.Atlanta.Feature.User.Model.UserEntity", "User")
                        .WithMany("Address")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RznMicro.Atlanta.Feature.User.Model.UserEntity", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
